version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vlaldis95/kittygram_backend
    env_file: .env.example
    volumes:
      - static:/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: vlaldis95/kittygram_frontend
    env_file: .env.example
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: vlaldis95/kittygram_gateway
    env_file: .env.example
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media/